Repository codinasion/codinasion, pull requests merged in 2023-07, with the labels that each got.

#4528 Reverse of a string
  program/program/print-reverse-of-a-string/print_reverse_of_a_string.pl
Labels: triage

#4527 Cube root of a number
  program/program/find-cube-root-of-a-number/find_cube_root_of_a_number.pl
Labels: triage

#4529 find_roots_of_quadratic_equation
  program/program/find-roots-of-quadratic-equation/find_roots_of_quadratic_equation.pl
Labels: triage

#4530 added find some of digit of a number in haskell
  program/program/find-sum-of-digits-of-a-number/find_sum_of_digit_of_a_number.hs
Labels: triage

#4531 Hexadecimal to binary
  program/program/convert-hexadecimal-to-binary/convert_hexadecimal_to_binary.pl
Labels: triage

#4532 Convert decimal to octal
  program/program/convert-decimal-to-octal/convert_decimal_to_octal.pl
Labels: triage

#4533 Create PrintNumberToWordsInIndianNumberingSystem.go
  program/program/find-the-transpose-of-a-matrix/program/find-the-transpose-of-a-matrixFindTheTransposeOfAMatrix.go
  program/program/print-number-to-words-in-indian-numbering-system/program/print-number-to-words-in-indian-numbering-system/PrintNumberToWordsInIndianNumberingSystem.go
Labels: triage

#4534 Decimal to octal
  program/program/convert-decimal-to-octal/convert_decimal_to_octal.dart
Labels: triage

#4535 Integer or Float
  program/program/check-integer-or-float/check_integer_or_float.dart
Labels: triage

#4536 Print ascii value of a character
  program/program/print-ascii-value-of-a-character/print-ascii-value-of-a-character.jl
Labels: triage

#4539 Added GO program to find lcm of two number Close:-965
  program/program/find-lcm-of-two-numbers/find_lcm_of_two_numbers.go
Labels: triage

#4537 Added Go programm to find sum of numbers by recursion Close issue :-2451
  program/program/find-sum-of-numbers-by-recursion/find_sum_of_numbers_by_recursion.go
Labels: triage

#4538 Added Go program to convert time from 12-24 hour Close:-2810
  program/program/convert-time-from-12-hour-to-24-hour-format/convert_time_from_12-hour_to_24-hour_format.go
Labels: triage

#4542 Solves convert string to sentencecase in rust #3731
  program/program/convert-string-to-sentencecase/convert_string_to_sentencecase.rs
Labels: triage

#4541 Solves convert string to reversecase in rust Vedant#3837
  program/program/convert-string-to-reversecase/convert_string_to_reversecase.rs
Labels: triage

#4545 bug : exclude suggestion from assignment
  github-bots/assign-me/src/index.ts
Labels: triage, LOC: XXL

#4543 Solves convert string to consonantcase #3325
  program/program/convert-string-to-consonantcase/convert_string_to_consonantcase.rs
Labels: triage, LOC: S

#4548 Added a GO program to find the maximum sum of a contiguous subarray
  program/program/find-the-maximum-sum-of-a-contiguous-subarray/find_the_maximum_sum_of_a_contiguous_subarray.go
Labels: triage

#4547 Added a GO program to convert string to pascalcase
  program/program/convert-string-to-pascalcase/convert_string_to_pascalcase.go
Labels: triage

#4550 Added a GO program to convert octal to decimal
  program/program/convert-octal-to-decimal/convert_octal_to_decimal.go
Labels: triage

#4549 A GO program to convert hexadecimal to binary
  program/program/convert-hexadecimal-to-binary/convert_hexadecimal_to_binary.go
Labels: triage

#4551 Solves print pattern 1 in rust #3073
  program/program/print-pattern-1/print_pattern_1.rs
Labels: triage

#4553 Flatten A Deeply Nested Array To Depth N.
  program/program/flatten-deeply-nested-array/flatten-deeply-nested-array.js
Labels: triage

#4554 Create PrintReverseOfANumberByRecursion.fs
  program/program/print-reverse-of-a-number-by-recursion/PrintReverseOfANumberByRecursion.fs
Labels: triage

#4555 Create find_sum_of_n_natural_numbers_using_formula.r
  program/program/find-sum-of-n-natural-numbers-using-formula/find_sum_of_n_natural_numbers_using_formula.r
Labels: triage

#4556 README, CONTRIBUTING & CODE_OF_CONDUCT Translations
  CODE_OF_CONDUCT-pt-br.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING-pt-br.md
  README-pt-br.md
  README.md
Labels: Translation

#4557 Cube root of a number
  program/program/find-cube-root-of-a-number/find_cube_root_of_a_number.rs
Labels: triage
