Repository codinasion/codinasion, pull requests merged in 2023-06, with the labels that each got.

#4468 Update .github/ISSUE_TEMPLATE/submit_program.yml
  .github/ISSUE_TEMPLATE/submit_program.yml
Labels: triage, LOC: XS

#4470 Create codeql.yml
  .github/workflows/codeql.yml
Labels: LOC: M

#4471 [ 🚧 WIP ] added GO program to convert string to alternatingcase
  program/program/convert-string-to-alternatingcase/convert_string_to_alternatingcase.go
Labels: LOC: S

#4469 created PrintAsciiValueOfAString.cs
  program/program/print-ascii-value-of-a-string/PrintAsciiValueOfAString.cs
Labels: triage, LOC: M

#4472 Add `api`
  .env.example
  .prettierignore
  apps/api/.eslintrc.js
  apps/api/.gitignore
  apps/api/README.md
  apps/api/app/(GitHub)/github/contributors/route.ts
  apps/api/app/(GitHub)/github/members/route.ts
  apps/api/app/(GitHub)/github/repos/route.ts
  apps/api/app/(Program)/program/[slug]/route.ts
  apps/api/app/(Program)/program/languages/[language]/route.ts
  apps/api/app/(Program)/program/languages/route.ts
  apps/api/app/(Program)/program/route.ts
  apps/api/app/route.ts
  apps/api/next.config.js
  apps/api/package.json
  apps/api/tsconfig.json
  pnpm-lock.yaml
  turbo.json
Labels: LOC: L

#4476 Create print_number_to_words.php
  program/program/print-number-to-words/print_number_to_words.php
Labels: triage, LOC: M

#4477 Solves #3900
  program/program/convert-rupees-to-paise/convert_rupees_to_paise.rs
Labels: triage, LOC: XS

#4479 Merge #4478
  apps/codinasion/public/Img/bg_dark.png
  apps/codinasion/public/Img/bg_light.png
  apps/codinasion/src/app/layout.tsx
  apps/codinasion/src/app/loading.tsx
  apps/codinasion/src/app/page.tsx
  apps/codinasion/src/components/Card/projectCard.tsx
  apps/codinasion/src/components/DarkModeToggle/index.tsx
  apps/codinasion/src/components/Home/index.tsx
  apps/codinasion/src/components/Home/projects.tsx
  apps/codinasion/src/layouts/index.tsx
  apps/codinasion/src/styles/globals.css
  apps/codinasion/tailwind.config.js
  apps/codinasion/tsconfig.json
  package.json
  pnpm-lock.yaml
Labels: LOC: XXL

#4481 Create find_the_maximum_sum_of_a_contiguous_subarray_(kadane's_algori…
  program/program/find-the-maximum-sum-of-a-contiguous-subarray-(kadane's-algorithm)/find_the_maximum_sum_of_a_contiguous_subarray_(kadane's_algorithm).php
Labels: triage

#4482 Vedant3584
  program/program/find-the-average-of-all-numbers-in-an-array/program/find_the_average_of_all_numbers_in_an_array.rs
Labels: triage

#4483 Vedant3795
  program/program/find-average-of-numbers/find_average_of_numbers.rs
  program/program/find-smallest-element-in-a-matrix/find_smallest_element_in_a_matrix.rs
Labels: triage, LOC: S

#4485 Vedant#3752
  program/program/print-numbers-from-1-to-n-without-using-a-loop/print_numbers_from_1_to_n_without_using_a_loop.rs
Labels: triage, LOC: S

#4484 Added a GO program to print inverted pyramid pattern
  program/program/print-inverted-pyramid-pattern/print_inverted_pyramid_pattern.go
Labels: triage, LOC: M

#4486 Convert string to kebabcase
  program/program/convert-string-to-kebabcase/ConvertStringToKebabcase.cs
Labels: triage, LOC: S

#4487 Print string of ascii values
  program/program/print-string-of-ascii-values/PrintStringOfAsciiValues.cs
Labels: triage, LOC: M

#4488 Dart vol of cube
  program/program/find-volume-of-cube/find_volume_of_cube.dart
Labels: triage, LOC: XS

#4489 Dart cube of num
  program/program/find-cube-of-a-number/find_cube_of_a_number.dart
Labels: triage, LOC: XS

#4490 Solves find the trace of a matrix #3492
  program/program/find-the-trace-of-a-matrix/find_the_trace_of_a_matrix.rs
Labels: triage, LOC: S

#4491 C# Split string into array of characters
  program/program/split-string-into-array-of-characters/SplitStringIntoArrayOfCharacters.cs
Labels: triage, LOC: S

#4492 C# Convert string to constant case
  program/program/convert-string-to-constantcase/ConvertStringToConstantcase.cs
Labels: triage, LOC: S

#4493 Find Smallest ElementIn a Matrix
  program/program/find-smallest-element-in-a-matrix/FindSmallestElementInAMatrix.rb
Labels: triage, LOC: XS

#4494 Add two matrices
  program/program/add-two-matrices/add_two_matrices.pl
Labels: triage, LOC: M

#4495 Solves print numbers from n to 1 without using loop #3346
  program/program/print-numbers-from-n-to-1-without-using-a-loop/print_numbers_from_n_to_1_without_using_a_loop.rs
Labels: triage, LOC: S

#4496 Maximum of n numbers
  program/program/find-maximum-of-n-numbers/find_maximum_of_n_numbers.pl
Labels: triage, LOC: XS

#4497 Inches to miles
  program/program/convert-inches-to-miles/ConvertInchesToMiles.fs
Labels: triage, LOC: XS

#4498 Pangram String
  program/program/check-pangram-string/check_pangram_string.dart
Labels: triage, LOC: XS

#4499 Created the code to convert time from 24-hour to 12-hour format
  program/program/convert-time-from-24-hour-to-12-hour-format/ConvertTimeFrom24-hourTo12-hourFormat.kt
Labels: triage, LOC: M

#4500 Created the code to rotate a matrix by 90 degrees
  program/program/cylindrically-rotate-a-matrix-by-90-degrees/CylindricallyRotateAMatrixBy90Degrees.kt
Labels: triage, LOC: M

#4502 Convert minutes to days (Ruby)
  program/program/convert-minutes-to-days/ConvertMinutesToDays.rb
Labels: triage

#4503 Print pascals triangle
  program/program/print-pascal's-triangle/PrintPascal'sTriangle.rb
Labels: triage

#4504 Convert string to reversecase (Dart)
  program/program/convert-string-to-reversecase/convert_string_to_reversecase.dart
Labels: triage, LOC: M

#4505 Convert days to hours (Dart)
  program/program/convert-days-to-hours/convert_days_to_hours.dart
Labels: triage, LOC: S

#4506 Added a GO program to convert string to vowelcase
  program/program/convert-string-to-vowelcase/convert_string_to_vowelcase.go
Labels: triage, LOC: S

#4507 Added GO program to convert string to constantcase
  program/program/convert-string-to-constantcase/convert_string_to_constantcase.go
Labels: triage, LOC: S

#4508 Added GO program to find sum of cubes of numbers by recursion
  program/program/find-sum-of-cubes-of-numbers-by-recursion/find_sum_of_cubes_of_numbers_by_recursion.go
Labels: triage, LOC: S

#4509 Added a GO program to print all prime numbers between two numbers
  program/program/print-all-prime-numbers-between-two-numbers/print_all_prime_numbers_between_two_numbers.go
Labels: triage, LOC: M

#4510 Added a GO program to print multiplication table
  program/program/print-multiplication-table/print_multiplication_table.go
Labels: triage, LOC: S

#4511 Solves find second smallest number in array in Rust #3388
  program/program/find-second-smallest-number-in-an-array/find_second_smallest_number_in_an_array.rs
Labels: triage, LOC: S

#4517 Solves Find sum of AP series in rust #3283
  program/program/find-second-smallest-number-in-an-array/find_second_smallest_number_in_an_array.rs
  program/program/find-sum-of-ap-series/find_sum_of_ap_series.rs
Labels: triage, LOC: S

#4512 a GO program to convert string to camelcase
  program/program/convert-string-to-camelcase/convert_string_to_camelcase.go
Labels: triage, LOC: S

#4513 GO program to print fibonacci series by recursion
  program/program/print-fibonacci-series-by-recursion/print_fibonacci_series_by_recursion.go
Labels: triage, LOC: S

#4516 Added Go program to calculate compound interest
  program/program/calculate-compound-interest/calculate_compound_interest.go
Labels: triage, LOC: S

#4518 find roots of quadratic equation
  program/program/find-roots-of-quadratic-equation/find_roots_of_quadratic_equation.fs
Labels: triage

#4519 Sum of GP Series
  program/program/find-sum-of-gp-series/find_sum_of_gp_series.php
Labels: triage

#4515 GO program to convert time from 24-hour to 12-hour format
  program/program/convert-time-from-24-hour-to-12-hour-format/convert_time_from_24-hour_to_12-hour_format.go
Labels: triage, LOC: M

#4514 Added ARmstrong GO program
  program/program/check-armstrong-number/check_armstrong_number.go
Labels: triage, LOC: M

#4523 find_roots_of_quadratic_equation
  program/program/find-roots-of-quadratic-equation/find_roots_of_quadratic_equation.r
Labels: triage

#4520 C# Convert Decimal to Hexadecimal
  program/program/convert-decimal-to-hexadecimal/ConvertDecimalToHexadecimal.cs
Labels: triage

#4521 Sum of GP series
  program/program/find-sum-of-gp-series/FindSumOfGpSeries.cs
Labels: triage

#4522 Reverse an array
  program/program/reverse-an-array/reverse_an_array.pl
Labels: triage

#4524 Average of numbers in an array
  program/program/find-the-average-of-all-numbers-in-an-array/find_the_average_of_all_numbers_in_an_array.pl
Labels: triage

#4525 Sum of AP Series
  program/program/find-sum-of-ap-series/find_sum_of_ap_series.php
Labels: triage

#4526 find_roots_of_quadratic_equation
  program/program/find-roots-of-quadratic-equation/find_roots_of_quadratic_equation.hs
Labels: triage
