Repository codinasion/codinasion, pull requests merged in 2023-12, with the labels that each got.

#4926 Rank of a matrix
  program/program/find-the-rank-of-a-matrix/find-the-rank-of-a-matrix.jl
Labels: triage, LOC: M

#4936 Create print-pascals-pyramid.rs
  program/program/print-pascals-triangle/print-pascals-pyramid.rs
Labels: triage, LOC: M

#4942 Create print_ascii_value_of_a_character.hs
  program/program/print-ascii-value-of-a-character/print_ascii_value_of_a_character.hs
Labels: triage, LOC: S

#4944 Merge strings
  merge-strings.py
  program/program/find-the-maximum-sum-of-a-contiguous-subarray/FindTheMaximumSumOfAContiguousSubarray.js
Labels: triage, LOC: S

#4950 Fix: node-fetch update error
  .env.example
  action/package.json
  merge-strings.py
  package.json
  pnpm-lock.yaml
Labels: bug, triage, LOC: M

#4961 Efficient way of solving maximum sum of a contiguos subarray
  program/program/find-the-maximum-sum-of-a-contiguous-subarray/FindTheMaximumSumOfAContiguousSubarray.js
Labels: triage, LOC: S

#4962 website: Update Nav
  pnpm-lock.yaml
  website/package.json
  website/src/app/_hero.tsx
  website/src/components/Footer/index.tsx
  website/src/components/Footer/powered-by-vercel.tsx
  website/src/components/Footer/social-icon.tsx
  website/src/components/Icon/index.tsx
  website/src/components/Navbar/docsearch-input.tsx
  website/src/components/Navbar/index.tsx
  website/src/components/Navbar/navbar-icons.tsx
  website/src/components/Navbar/navbar-links.tsx
  website/src/components/Navbar/theme-switch.tsx
  website/src/components/ScrollNavigartion/index.tsx
  website/src/data/footer.ts
  website/src/data/sitemetadata.ts
  website/src/styles/docsearch.css
  website/src/types/footer.ts
  website/src/types/sitemetadata.ts
  website/tailwind.config.ts
Labels: triage, website, LOC: XXL

#4965 Sum of AP series
  program/program/find-sum-of-ap-series/FindSumOfApSeries.kt
Labels: triage, LOC: M

#4966 Print pattern 1
  program/program/print-pattern-1/PrintPattern1.kt
Labels: triage, LOC: S

#4968 Add Kotlin program to find the adjoint of a matrix
  program/program/find-the-adjoint-of-a-matrix/FindTheAdjointOfAMatrix.kt
Labels: triage, LOC: M
