Repository codinasion/codinasion, pull requests merged in 2023-08, with the labels that each got.

#4560 Added go program to find GCD of 2 numbers by recursion CLOSE:3847
  program/program/find-gcd-of-two-numbers-by-recursion/find_gcd_of_two_numbers_by_recursion.go
Labels: triage, LOC: S

#4561 Added go program to find sum of GP series
  program/program/find-sum-of-gp-series/find_sum_of_gp_series.go
Labels: triage, LOC: S

#4559 Added Go program to print numbers to words CLOSE:1945
  program/program/print-number-to-words/print-number-to-words.go
Labels: triage, LOC: M

#4558 Swap two numbers
  program/program/swap-two-numbers/SwapTwoNumbers.fs
Labels: triage, LOC: XS

#4563 Add seconds to minutes in rust
  program/program/convert-seconds-to-minutes/convert_seconds_to_minutes.rs
Labels: triage

#4562 find the maximum sum of a contiguous subarray (circular)
  program/program/find-the-maximum-sum-of-a-contiguous-subarray-(circular)/FindTheMaximumSumOfAContiguousSubarray(circular).ts
Labels: triage

#4566 A GO program to convert decimal to binary
  program/program/convert-decimal-to-binary/convert_decimal_to_binary.go
Labels: triage, LOC: S

#4567 A GO program to convert hexadecimal to decimal
  program/program/convert-hexadecimal-to-decimal/convert_hexadecimal_to_decimal.go
Labels: triage, LOC: M

#4572 Add days to seconds in rust
  program/program/convert-days-to-seconds/convert_days_to_seconds.rs
Labels: triage

#4570 Close:424 Added GO program to convert binary to octal
  program/program/convert-binary-to-octal/convert_binary_to_octal.go
Labels: triage

#4573 Add minutes to seconds in rust
  program/program/convert-minutes-to-seconds/convert_minutes_to_seconds.rs
Labels: triage

#4568 a GO program to print string of ascii values
  program/program/print-string-of-ascii-values/print_string_of_ascii_values.go
Labels: triage

#4571 Add seconds to weeks in rust
  program/program/convert-seconds-to-weeks/convert_seconds_to_weeks.rs
Labels: triage

#4569 Close:2493 Added GO program to find the rank of a matrix
  program/program/find-the-rank-of-a-matrix/find_the_rank_of_a_matrix.go
Labels: triage

#4574 Fix: Program build error
  CONTRIBUTING-pt-br.md
  README-pt-br.md
  README.md
  apps/program/src/app/languages/[language]/page.tsx
  apps/program/src/components/Program/ProgramCard.tsx
  packages/internal/shared/src/components/Comment/index.tsx
  program/data/languages.json
  program/data/programs.json
Labels: bug, LOC: L

#4576 Update FindLcmOfTwoNumbersByRecursion.ts
  program/program/find-lcm-of-two-numbers-by-recursion/FindLcmOfTwoNumbersByRecursion.ts
Labels: triage, LOC: S

#4575 [ 🚧 WIP ] Add ConvertBinaryToHexadecimal.cs for C#
  program/program/convert-binary-to-hexadecimal/ConvertBinaryToHexadecimal.cs
Labels: LOC: M

#4577 ConvertStringToSentencecase by Ari Porat
  program/program/convert-string-to-sentencecase/ConvertStringToSentencecase.cs
Labels: triage

#4582 Fix #4581
  program/program/convert-string-to-sentencecase/README.md
Labels: documentation
