Repository codinasion/codinasion, pull requests merged in 2024-04, with the labels that each got.

#5606 Write a Haskell program to find the largest three elements in an array #5173
  program/program/find-the-largest-three-elements-in-an-array/find_the_largest_three_elements_in_an_array.hs
  program/program/find-the-largest-two-elements-in-an-array/find_the_largest_two_elements_in_an_array.swift
Labels: triage, LOC: M

#5615 Write a Ruby program to convert standard date format to julian date a…
  program/program/convert-standard-date-format-to-julian-date-and-vice-versa/ConvertStandardDateFormatToJulianDateAndVice-versa.rb
Labels: triage, LOC: S

#5613 Write a GO program to implement selection sort
  program/program/implement-selection-sort/implement_selection_sort.go
Labels: triage, LOC: M

#5614 Write a C# program to convert standard date format to julian date and…
  program/program/convert-standard-date-format-to-julian-date-and-vice-versa/ConvertStandardDateFormatToJulianDateAndVice-versa.cs
Labels: triage, LOC: M

#5619 Implement ternary search
  program/program/implement-ternary-search/implement_ternary_search.dart
Labels: triage, LOC: M

#5617 Create FindTheTransposeOfAMatrix.swift
  program/program/find-the-transpose-of-a-matrix/FindTheTransposeOfAMatrix.swift
Labels: triage, LOC: M

#5638 issue#1742
  program/program/find-the-cofactor-of-a-matrix/FindTheCofactorOfAMatrix.swift
Labels: triage, LOC: M

#5634 Implement selection sort algorithm in C#
  program/program/implement-selection-sort/ImplementSelectionSort.cs
Labels: triage, LOC: M

#5633 Fixed issue #3785 : Write a Haskell program to find smallest element in a matrix
  program/program/find-smallest-element-in-a-matrix/FindSmallestElementInAMatrix.hs
Labels: triage, LOC: S

#5629 Date conversion Haskell program added
  program/program/convert-standard-date-format-to-julian-date-and-vice-versa/convert_standard_date_format_to_julian_date_and_vice-versa.hs
Labels: triage, LOC: S

#5625 Haskell implement ternary search
  program/program/implement-ternary-search/implement_ternary_search.hs
Labels: triage, LOC: S

#5618 Create CheckValidDate.swift
  program/program/check-valid-date/CheckValidDate.swift
Labels: triage, LOC: S

#5620 Create FindTheRankOfAMatrix.swift
  program/program/find-the-rank-of-a-matrix/FindTheRankOfAMatrix.swift
Labels: triage, LOC: M

#5627 Swift dec to hex
  program/program/convert-decimal-to-hexadecimal/ConvertDecimalToHexadecimal.swift
Labels: triage, LOC: M

#5644 Create ConvertStringToPascalcase.swift
  program/program/convert-string-to-pascalcase/ConvertStringToPascalcase.swift
Labels: triage, LOC: S

#5645 Create printPattern1.scala
  program/program/print-pattern-1/printPattern1.scala
Labels: triage, LOC: S

#5624 Julia implement ternary search
  program/program/implement-ternary-search/implement-ternary-search.jl
Labels: triage, LOC: M

#5630 Date conversion F# program added
  program/program/convert-standard-date-format-to-julian-date-and-vice-versa/ConvertStandardDateFormatToJulianDateAndVice-versa.fs
Labels: triage, LOC: S

#5631 Perl program of jump search added
  program/program/implement-jump-search/implement_jump_search.pl
Labels: triage, LOC: M

#5649 Create find-average-of-numbers-by-recursion.jl
  program/program/find-average-of-numbers-by-recursion/find-average-of-numbers-by-recursion.jl
Labels: triage, LOC: S

#5632 Fixed Issue #5185 Write a Swift program to find Largest Three Numbers in An Array
  program/program/find-largest-number-in-an-array/FindLargestThreeNumbersInAnArray.swift
Labels: triage, LOC: S

#5656 [Closed] Create FindLcmOfTwoNumbersByRecursion.fs issue # 343
  program/program/find-lcm-of-two-numbers-by-recursion/FindLcmOfTwoNumbersByRecursion.fs
Labels: triage, LOC: S

#5635 Write a Swift program to find the maximum sum of a contiguous subarra…
  program/program/find-the-maximum-sum-of-a-contiguous-subarray-(kadanes-algorithm)/FindTheMaximumSumOfAContiguousSubarray(kadane'sAlgorithm).swift
Labels: triage, LOC: S

#5636 issue#1142
  program/program/convert-hexadecimal-to-octal/ConvertHexadecimalToOctal.swift
Labels: triage, LOC: M

#5642 Haskell Program to convert Octal to Binary
  program/program/convert-octal-to-binary/convert_octal_to_binary.hs
Labels: triage, LOC: S

#5662 convert from octal to decimal
  program/program/convert-octal-to-decimal/convertOctalToDecimal.rb
Labels: triage, LOC: S

#5668 Added Perl Program to find the trace of a matrix (codinasion#3487)
  program/program/find-the-trace-of-a-matrix/FindTheTraceOfAMatrix.pl
Labels: triage, LOC: M

#5661 power using recursion
  program/program/find-power-of-a-number-by-recursion/FindFactorialOfANumberByRecursion.r
Labels: triage, LOC: S

#5672 Update find_factorial_of_a_number.py
  program/program/find-factorial-of-a-number/find_factorial_of_a_number.py
Labels: triage, LOC: S

#5626 Swift adjoint matrix
  program/program/find-the-cofactor-of-a-matrix/FindTheAdjointOfAMatrix.swift
Labels: triage, LOC: M

#5673 Added Go program to Implement Jump Search (#5260)
  program/program/implement-jump-search/ImplementJumpSearch.go
Labels: triage, LOC: M

#5671 Update add_two_matrices.py
  program/program/add-two-matrices/add_two_matrices.py
Labels: triage, LOC: M

#5637 issue#356
  program/program/find-lcm-of-two-numbers-by-recursion/FindLcmOfTwoNumbersByRecursion.swift
Labels: triage, LOC: S

#5681 Added Perl Program to find maximum sum of a contiguous subarray.
  program/program/find-the-maximum-sum-of-a-contiguous-subarray/FindTheMaximumSumOfAContiguousSubarray.pl
Labels: triage, LOC: S

#5667 Implemented linear search in Scala
  program/program/implement-linear-search/ImplementLinearSearch.sc
Labels: triage, LOC: S

#5687 Added Perl program to print Inverted Pyramid Pattern
  program/program/print-inverted-pyramid-pattern/PrintInvertedPyramidPattern.pl
Labels: triage, LOC: S

#5677 Update swap_two_numbers.py
  program/program/swap-two-numbers/swap_two_numbers.py
Labels: triage, LOC: XS

#5676 Update find_average_of_numbers.py
  program/program/find-average-of-numbers/find_average_of_numbers.py
Labels: triage, LOC: XS

#5655 Issue fixed #332 Write a R program to convert feet to miles
  program/program/convert-feet-to-miles/convert-feet-to-miles.r
Labels: triage, LOC: S

#5658 [Closed] Create find_lcm_of_two_numbers_by_recursion.rs ISSUE # 354
  program/program/find-lcm-of-two-numbers-by-recursion/find_lcm_of_two_numbers_by_recursion.rs
Labels: triage, LOC: M

#5691 Adding Program to Find the Two Smallest Elements in An Array in Rust
  FindTheSmallestTwoElementsInAnArray.rs
Labels: triage, LOC: S

#5648 Create find_the_trace_of_a_matrix.pl
  program/program/find-the-trace-of-a-matrix/find_the_trace_of_a_matrix.pl
Labels: triage, LOC: M
