Repository codinasion/codinasion, pull requests merged in 2024-05, with the labels that each got.

#5683 Added F# program to convert string to pascal case
  program/program/convert-string-to-pascalcase/ConvertStringToPascalcase.fs
Labels: triage, LOC: S

#5690 Added Perl program to convert octal to hexadecimal
  program/program/convert-octal-to-hexadecimal/convert-octal-to-hexadecimal.pl
Labels: triage, LOC: M

#5689 Added Perl program to convert number to words in Indian numbering system
  program/program/print-number-to-words-in-indian-numbering-system/PrintNumberToWordsInIndianNumberingSystem.pl
Labels: triage, LOC: M

#5688 Added Perl program to find sum of cubes of numbers by recursion
  program/program/find-sum-of-cubes-of-numbers-by-recursion/FindSumOfCubesOfNumbersByRecursion.pl
Labels: triage, LOC: S

#5675 Update calculate_the_permutation_of_n_objects_taken_r_at_a_time.py
  program/program/calculate-the-permutation-of-n-objects-taken-r-at-a-time/calculate_the_permutation_of_n_objects_taken_r_at_a_time.py
Labels: triage, LOC: S

#5643 Create convert_kilometers_to_miles.rs
  program/program/convert-kilometers-to-miles/convert_kilometers_to_miles.rs
Labels: triage, LOC: S

#5686 Upper case R
  program/program/check-upper-case/check_upper_case.r
Labels: triage, LOC: S

#5682 Added Perl Program to calculate the permutation of n objects taken r at a time
  program/program/calculate-the-permutation-of-n-objects-taken-r-at-a-time/CalculateThePermutationOfNObjectsTakenRAtATime.pl
Labels: triage, LOC: S

#5678 Update print_reverse_of_a_number.py
  program/program/print-reverse-of-a-number/print_reverse_of_a_number.py
Labels: triage, LOC: S

#5666 Implemented program to find the smallest three elements in an array in C#
  program/program/find-the-smallest-three-elements-in-an-array/FindTheSmallestThreeElementsInAnArray.cs
Labels: triage, LOC: M

#5616 Create FindSumOfSquaresOfNumbersByRecursion.swift
  program/program/find-sum-of-squares-of-numbers-by-recursion/FindSumOfSquaresOfNumbersByRecursion.swift
Labels: triage, LOC: S

#5659 Create find-lcm-of-two-numbers-by-recursion.jl ISSUE # 347
  program/program/find-lcm-of-two-numbers-by-recursion/find-lcm-of-two-numbers-by-recursion.jl
Labels: triage, LOC: S

#5680 Added Rust Program to find weekend days from number of years #4390
  program/program/find-weekend-days-from-number-of-years/FindWeekendDaysFromNumberOfYears.rs
Labels: triage, LOC: M

#5665 Scala program to convert string to reverse case
  ConvertStringToReversecase.sc
Labels: triage, LOC: S

#5660 Selection sort implemented in Scala
  program/program/implement-selection-sort/ImplementSelectionSort.sc
Labels: triage, LOC: S

#5663 Implemented jump search in Scala
  ImplementJumpSearch.sc
  program/program/implement-jump-search/ImplementJumpSearch.sc
Labels: triage, LOC: M

#5664 Implemented Binary Search in Perl
  ImplementBinarySearch.pl
Labels: triage, LOC: S

#5674 Greeshmanth1 patch 1
  program/program/calculate-the-combination-of-n-objects-taken-r-at-a-time/calculate_the_combination_of_n_objects_taken_r_at_a_time.py
Labels: triage, LOC: S

#5700 issue#2540
  program/program/find-the-determinant-of-a-matrix/FindTheDeterminantOfAMatrix.kt
Labels: triage, LOC: S

#5701 issue#2351
  program/program/find-the-eigenvectors-of-a-matrix/FindTheEigenvectorsOfAMatrix.kt
Labels: triage, LOC: S

#5705 Feature/find the cofactor of a matrix
  program/program/find-the-cofactor-of-a-matrix/find_the_cofactor_of_a_matrix.scala
Labels: triage, LOC: M

#5706 Feature/find the adjoint of a matrix
  program/program/find-the-adjoint-of-a-matrix/findTheAdjointOfAMatrix.scala
Labels: triage, LOC: L

#5714 Create find_maximum_of_n_numbers.dart
  program/program/find-maximum-of-n-numbers/find_maximum_of_n_numbers.dart
Labels: triage, LOC: S
