Repository codinasion/codinasion, pull requests merged in 2024-03, with the labels that each got.

#5564 Write a Java program to convert temperature from celsius to kelvin
  program/program/convert-temperature-from-celsius-to-kelvin/ConvertTemperatureFromCelsiusToKelvin.java
Labels: triage, LOC: S

#5570 Added convert-temperature-from-celsius-to-kelvin for Rust
  program/program/convert-temperature-from-celsius-to-kelvin/convert_temperature_from_celsius_to_kelvin.rs
Labels: triage, LOC: S

#5575 Perl program of Celsius to Kelvin added
  program/program/convert-celsius-to-kelvin/conver_celsius_to_kelvin.pl
Labels: triage, LOC: XS

#5590 Write a Kotlin program to convert temperature from celsius to kelvin
  program/program/convert-temperature-from-celsius-to-kelvin/ConvertTemperatureFromCelsiusToKelvin.kt
Labels: triage, LOC: S

#5586 Write a Scala program to convert temperature from celsius to kelvin
  program/program/convert-temperature-from-celsius-to-kelvin/convertTemperatureFromCelsiusToKelvin.scala
Labels: triage, LOC: S

#5574 Swift program of Celsius to Kelvin Added
  program/program/convert-celsius-to-kelvin/convert_celsius_to_kelvin.swift
Labels: triage, LOC: XS

#5591 Write a PHP program to convert temperature from celsius to kelvin
  program/program/convert-temperature-from-celsius-to-kelvin/convert_temperature_from_celsius_to_kelvin.php
Labels: triage, LOC: S

#5569 Write a C++ program to convert temperature from celsius to kelvin
  program/program/convert-temperature-from-celsius-to-kelvin/ConvertTemperatureFromCelsiusToKelvin.cpp
Labels: triage, LOC: S

#5592 Write a Ruby program to convert temperature from celsius to kelvin
  program/program/convert-temperature-from-celsius-to-kelvin/ConvertTemperatureFromCelsiusToKelvin.rb
Labels: triage, LOC: S

#5572 Added checkArmstrongNumber in Scala
  program/program/check-armstrong-number/checkArmstrongNumber.scala
Labels: triage, LOC: S

#5577 added calculateThePermutationOfNObjectsTakenRAtATime in scala
  program/program/calculate-the-combination-of-n-objects-taken-r-at-a-time/calculateTheCombinationOfNObjectsTakenRAtATime.scala
Labels: triage, LOC: S

#5578 added Find digital root of a number in Scala
  program/program/find-digital-root-of-a-number/findDigitalRootOfANumber.scala
Labels: triage, LOC: S

#5576 Julia program of Celsius to Kelvin added
  program/program/convert-temperature-from-celsius-to-kelvin/convert-temperature-from-celsius-to-kelvin.jl
Labels: triage, LOC: XS

#5573 Typescript Celsius to Kelvin Program added
  program/program/convert-temperature-from-celsius-to-kelvin/ConvertTemperatureFromCelsiusToKelvin.ts
Labels: triage, LOC: XS

#5580 print_pattern_1.pl
  program/program/print-diamond-pattern/print_pattern_1.pl
Labels: triage, LOC: S

#5584 solution
  program/program/convert-standard-date-format-to-julian-date-and-vice-versa/convert_standard_date_format_to_julian_date_and_vice_versa.dart
Labels: triage, LOC: M

#5571 Add a C program to convert temperature from celsius to kelvin
  program/program/convert-temperature-from-celsius-to-kelvin/ConvertTemperatureFromCelsiusToKelvin.c
Labels: triage, LOC: S

#5579 Implement ternary search in GO
  program/program/implement-ternary-search/implement_ternary_search.go
Labels: triage, LOC: M

#5589 Write a JavaScript program to convert temperature from celsius to kelvin
  program/program/convert-temperature-from-celsius-to-kelvin/ConvertTemperatureFromCelsiusToKelvin.js
Labels: triage, LOC: XS

#5588 Write a GO program to convert temperature from celsius to kelvin
  program/program/convert-temperature-from-celsius-to-kelvin/convert_temperature_from_celsius_to_kelvin.go
Labels: triage, LOC: S

#5587 Write a Dart program to convert temperature from celsius to kelvin
  program/program/convert-temperature-from-celsius-to-kelvin/convert_temperature_from_celsius_to_kelvin.dart
Labels: triage, LOC: S

#5582 Celsius to Kelvin #F program added
  program/program/convert-temperature-from-celsius-to-kelvin/ConvertTemperatureFromCelsiusToKelvin.fs
Labels: triage, LOC: XS

#5583 Create find-sum-of-gp-series.jl
  program/program/find-sum-of-gp-series/find-sum-of-gp-series.jl
Labels: triage, LOC: S

#5594 Perl program of Standard date conversion added
  program/program/convert-standard-date-format-to-julian-date-and-vice-versa/convert_standard_date_format_to_julian_date_and_vice-versa.pl
Labels: triage, LOC: S

#5595 Kotlin program of date conversion added
  program/program/convert-standard-date-format-to-julian-date-and-vice-versa/ConvertStandardDateFormatToJulianDateAndVice-versa.kt
Labels: triage, LOC: S

#5596 Haskell program of Celsius to Kelvin added
  program/program/convert-temperature-from-celsius-to-kelvin/convert_temperature_from_celsius_to_kelvin.hs
Labels: triage, LOC: S

#5597 Julia program of Standard date conversion added
  program/program/convert-standard-date-format-to-julian-date-and-vice-versa/convert-standard-date-format-to-julian-date-and-vice-versa.jl
Labels: triage, LOC: S

#5593 Create PrintDiamondPattern.jl
  program/program/print-diamond-pattern/PrintDiamondPattern.jl
Labels: triage, LOC: S

#5565 Convert Celsius to Kelvin C# Function
  program/program/convert-temperature-from-celsius-to-kelvin/convert_temperature_from_celsius_to_kelvin.cs
Labels: triage, LOC: XS

#5598 GO program of standard date conversion added
  program/program/convert-standard-date-format-to-julian-date-and-vice-versa/convert_standard_date_format_to_julian_date_and_vice-versa.go
Labels: triage, LOC: M

#5599 Largest 3 elements
  program/program/find-the-largest-three-elements-in-an-array/find-the-largest-three-elements-in-an-array.jl
Labels: triage, LOC: S

#5600 Smallest two elements
  program/program/find-the-smallest-two-elements-in-an-array/find-the-smallest-two-elements-in-an-array.jl
Labels: triage, LOC: S

#5601 Largest 2 elements
  program/program/find-the-largest-two-elements-in-an-array/find-the-largest-two-elements-in-an-array.jl
Labels: triage, LOC: S

#5585 Solves issue with swift not finding the largest two elements correctly
  program/program/find-the-largest-two-elements-in-an-array/find_the_largest_two_elements_in_an_array.swift
  program/program/implement-linear-search/ImplementLinearSearch.fs
Labels: triage, LOC: M

#5568 Haskell program implementing the Jump Search algorithm
  program/program/implement-jump-search/implement_jump_search.hs
Labels: triage, LOC: M

#5602 Rename files
  program/program/convert-standard-date-format-to-julian-date-and-vice-versa/ConvertStandardDateFormatToJulianDateAndViceVersa.kt
  program/program/convert-standard-date-format-to-julian-date-and-vice-versa/convert_standard_date_format_to_julian_date_and_vice_versa.go
  program/program/convert-standard-date-format-to-julian-date-and-vice-versa/convert_standard_date_format_to_julian_date_and_vice_versa.pl
  program/program/convert-temperature-from-celsius-to-kelvin/ConvertTemperatureFromCelsiusToKelvin.cs
  program/program/convert-temperature-from-celsius-to-kelvin/ConvertTemperatureFromCelsiusToKelvin.swift
  program/program/convert-temperature-from-celsius-to-kelvin/convert_temperature_from_celsius_to_kelvin.pl
  program/program/find-the-largest-two-elements-in-an-array/FindTheLargestTwoElementsInAnArray.swift
  program/program/print-diamond-pattern/print-diamond-pattern.jl
  program/program/print-diamond-pattern/print_diamond_pattern.pl
  program/program/print-diamond-pattern/print_pattern_1.pl
Labels: triage, LOC: M

#5603 Special character
  program/program/check-special-character/check_special_character.dart
Labels: triage, LOC: S

#5604 Create FindAverageOfNumbersByRecursion.dart
  program/program/find-average-of-numbers-by-recursion/FindAverageOfNumbersByRecursion.dart
Labels: triage, LOC: S
