Repository codinasion/codinasion, pull requests merged in 2024-01, with the labels that each got.

#4969 Smallest element
  program/program/find-smallest-number-in-an-array/FindSmallestNumberInAnArray.fs
Labels: triage, LOC: XS

#4975 Create print_inverted_pyramid_pattern.dart
  program/program/print-inverted-pyramid-pattern/print_inverted_pyramid_pattern.dart
Labels: triage, LOC: S

#4978 website: Add Breadcrumb,Comment
  pnpm-lock.yaml
  website/package.json
  website/src/app/program/[slug]/page.tsx
  website/src/components/Breadcrumb/index.tsx
  website/src/components/Comment/index.tsx
  website/src/components/MarkdownPreview/Code.tsx
  website/src/components/Program/program-component.tsx
  website/src/components/Program/program-detail-component.tsx
Labels: triage, website, LOC: L

#4979 Create print_inverted_pyramid_pattern.hs
  program/program/print-inverted-pyramid-pattern/print_inverted_pyramid_pattern.hs
Labels: triage, LOC: XS

#4980 action: Test: Submit program
  .github/workflows/submit-program.yml
  action/README.md
  action/action.yml
  action/dist/index.js
  action/src/action/submit-program comment-close.ts
  action/src/action/submit-program.ts
  action/src/main.ts
  action/src/submit-program/close-issue.ts
  action/src/submit-program/create-issue-comment.ts
  action/src/submit-program/submit-program-comment-close.ts
  action/src/submit-program/submit-program.ts
  action/src/submit-program/types.ts
Labels: triage, action, LOC: XL

#4981 Add submit program issue template
  .github/ISSUE_TEMPLATE/submit-program.yml
Labels: triage, LOC: M

#4982 Add default issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: triage, LOC: L

#4985 Fix: actions/runs/7411773963
  .github/workflows/submit-program.yml
Labels: bug, triage, LOC: XS

#4987 Fix: actions/runs/7411880342/job/20167422008
  .github/workflows/submit-program.yml
Labels: bug, triage, LOC: XS

#4989 action: Update: Submit Program Comment
  action/dist/index.js
  action/src/submit-program/submit-program-comment-close.ts
  action/src/submit-program/submit-program.ts
Labels: triage, LOC: S, action

#4992 Remove extra space
  action/dist/index.js
  action/src/submit-program/submit-program.ts
Labels: triage, LOC: XS

#4995 Accept Program #4946
  program/data/programs.json
Labels: triage, program, LOC: S

#4996 action: Test: Auto Create & Auto Track Issues
  .github/workflows/auto-create-issue.yml
  .github/workflows/auto-track-issue.yml
  .github/workflows/check-dist.yml
  .github/workflows/ci.yml
  .github/workflows/collect-contributors-data.yml
  .github/workflows/collect-program-data.yml
  .github/workflows/release.yml
  .github/workflows/submit-program.yml
  .github/workflows/tweet-gfi-data.yml
  .github/workflows/tweet-meme.yml
  .github/workflows/tweet-quote-data.yml
  .github/workflows/tweet-trending-repos-data.yml
  action/action.yml
  action/dist/index.js
  action/src/action/auto-create-issue.ts
  action/src/action/auto-track-issue.ts
  action/src/main.ts
  action/src/submit-program/auto-create-issue.ts
  action/src/submit-program/auto-track-issue.ts
  action/src/submit-program/create-issue.ts
  action/src/submit-program/file-naming.ts
  action/src/submit-program/types.ts
  action/src/submit-program/update-issue.ts
Labels: triage, LOC: XXL, action

#4998 Auto Create Issue - 1
  program/data/programs.json
  program/program/reverse-words-in-a-string/README.md
Labels: triage, LOC: S

#5019 action: Update: Action
  .github/workflows/auto-create-issue.yml
  .github/workflows/auto-track-issue.yml
  action/dist/index.js
  action/src/submit-program/auto-create-issue.ts
  action/src/submit-program/auto-track-issue.ts
Labels: triage, LOC: S, action

#5020 Create ReverseWordsInAString.ts
  program/program/reverse-words-in-a-string/ReverseWordsInAString.ts
Labels: triage, LOC: XS

#5021 Determinant of a matrix
  program/program/find-the-determinant-of-a-matrix/find_the_determinant_of_a_matrix.php
Labels: triage, LOC: M

#5024 Feature/reverse words
  program/program/reverse-words-in-a-string/ReverseWordsInAString.c
Labels: triage, LOC: M

#5025 Added java program to reverse the words in a string
  program/program/reverse-words-in-a-string/ReverseWordsInAString.java
Labels: triage, LOC: M

#5026 Added python program to reverse words in a string
  program/program/reverse-words-in-a-string/reverse_words_in_a_string.py
Labels: triage, LOC: S

#5028 Create ReverseWordsInAString.cs
  program/program/reverse-words-in-a-string/ReverseWordsInAString.cs
Labels: triage, LOC: S

#5029 added scala program to reverse words in a string
  program/program/reverse-words-in-a-string/reverseWordsInAString.scala
Labels: triage, LOC: S

#5027 Adding a PHP program that reverses words in a string
  program/program/reverse-words-in-a-string/reverse_words_in_a_string.php
Labels: triage, LOC: S

#5030 action: Patch action & Move program script
  .gitignore
  action/dist/index.js
  action/src/submit-program/auto-track-issue.ts
  scripts/program/check_duplicate_file_extensions.py
  scripts/program/check_file_names.py
  scripts/program/check_unknown_extensions.py
  scripts/program/rename_files.py
Labels: triage, program, LOC: S, action

#5032 Accept Program #5031
  program/data/programs.json
Labels: triage, program, LOC: S

#5056 Accept Program #5055
  program/data/programs.json
Labels: triage, program, LOC: XS

#5058 Accept Program #5057
  program/data/programs.json
Labels: triage, program, LOC: XS

#5063 Accept Program #5059
  program/data/programs.json
Labels: triage, program, LOC: XS

#5064 Accept Program #5060
  program/data/programs.json
Labels: triage, program, LOC: XS

#5066 Accept Program #5062
  program/data/programs.json
Labels: triage, program, LOC: XS

#5065 Accept Program #5061
  program/data/programs.json
Labels: triage, program, LOC: XS

#5067 Update program data
  program/data/programs.json
Labels: triage, LOC: XS

#5095 Accept Program #5090
  program/data/programs.json
Labels: triage, program, LOC: S

#5094 Accept Program #5092
  program/data/programs.json
Labels: triage, program, LOC: S

#5069 Auto Create Issue - 4
  program/data/programs.json
  program/program/find-the-smallest-two-elements-in-an-array/README.md
Labels: triage, LOC: S

#5097 Fix program.json
  program/data/programs.json
Labels: triage, LOC: S

#5091 Create FindTheLargestTwoElementsInAnArray.cs
  program/program/find-the-largest-two-elements-in-an-array/FindTheLargestTwoElementsInAnArray.cs
Labels: triage, LOC: M

#5105 smallest two elemtnts TS
  program/program/find-the-smallest-two-elements-in-an-array/FinfTheSmallestTwoElementsInAnArray.ts
Labels: triage, LOC: S

#5098 Create FindTheSmallestTwoElementsInAnArray.cs
  program/program/find-the-smallest-two-elements-in-an-array/FindTheSmallestTwoElementsInAnArray.cs
Labels: triage, LOC: M

#5109 Auto Create Issue - 5
  program/data/programs.json
  program/program/implement-ternary-search/README.md
Labels: triage, LOC: M

#5134 Auto Create Issue - 6
  program/data/programs.json
  program/program/move-all-zeroes-to-end-of-array/README.md
Labels: triage, LOC: S

#5131 Reverse words feature
  program/program/reverse-words-in-a-string/ReverseWordsInAString.cpp
Labels: triage, LOC: M

#5106 feat: find the largest tow elements
  program/program/find-the-largest-two-elements-in-an-array/FindTheLargestTwoElementsInAnArray.ts
Labels: triage, LOC: S

#5132 Python find smallest two elements in array
  program/program/find-the-smallest-two-elements-in-an-array/find-the-smallest-two-elements-in-an-array.py
Labels: triage, LOC: S

#5107 Create FindTheSmallestTwoElementsInAnArray.js
  program/program/find-the-smallest-two-elements-in-an-array/FindTheSmallestTwoElementsInAnArray.js
Labels: triage, LOC: XS

#5164 acton: Fix: Collect program data
  .github/workflows/collect-program-data.yml
  program/program/find-the-smallest-two-elements-in-an-array/FindTheSmallestTwoElementsInAnArray.ts
  program/program/find-the-smallest-two-elements-in-an-array/find_the_smallest_two_elements_in_an_array.py
Labels: triage, program, LOC: XS, action

#5166 Auto Create Issue - 7
  program/data/programs.json
  program/program/find-the-largest-three-elements-in-an-array/README.md
Labels: triage, LOC: S

#5155 Feature reverse words dart
  program/program/reverse-words-in-a-string/reverse_words_in_a_string.dart
Labels: triage, LOC: S

#5156 Feature find smallest two elements
  program/program/find-the-smallest-two-elements-in-an-array/find_the_smallest_two_elements_in_an_array.r
Labels: triage, LOC: S

#5157 Program to Implement Ternary Search in java
  program/program/implement-ternary-search/ImplementTernarySearch.java
Labels: triage, LOC: M

#5159 Add a Python program to move all zeroes to end of array
  program/program/move-all-zeroes-to-end-of-array/move_all_zeroes_to_end_of_array.py
Labels: triage, LOC: S

#5162 Add a Java program to move all zeroes to end of array
  program/program/move-all-zeroes-to-end-of-array/MoveAllZeroesToEndOfArray.java
Labels: triage, LOC: M

#5163 Create move-all-zeroes-to-end-of-array.py
  program/program/move-all-zeroes-to-end-of-array/move-all-zeroes-to-end-of-array.py
Labels: triage, LOC: XS

#5158 Create reverse_words_in_a_string.go
  program/program/reverse-words-in-a-string/reverse_words_in_a_string.go
Labels: triage, LOC: S

#5187 Add a GO program to move all zeroes to end of array
  program/program/move-all-zeroes-to-end-of-array/move_all_zeroes_to_end_of_array.go
Labels: triage, LOC: S

#5160 Python program: moves zeroes to end of array
  program/program/move-all-zeroes-to-end-of-array/move_all_zeroes_to_end_of_array.py
Labels: triage, LOC: S

#5161 Two largest elements in array
  program/program/find-the-largest-two-elements-in-an-array/find_the_largest_two_elements_in_an_array.py
Labels: triage, LOC: S

#5188 Rename program files
  program/program/move-all-zeroes-to-end-of-array/move-all-zeroes-to-end-of-array.py
  program/program/move-all-zeroes-to-end-of-array/move_all_zeroes_to_end_of_array.py
Labels: triage, program, LOC: S

#5193 Auto Create Issue - 8
  program/data/programs.json
  program/program/implement-binary-search/README.md
Labels: triage, LOC: M

#5189 Feature/reverse words fsharp
  program/program/reverse-words-in-a-string/ReverseWordsInAString.fs
Labels: triage, LOC: S

#5190 Program to find the three largest elements in an array
  program/program/find-the-largest-three-elements-in-an-array/find_the_largest_three_elements_in_an_array.py
Labels: triage, LOC: S

#5191 Implemented the program to find largest three numbers from an array
  program/program/find-the-largest-three-elements-in-an-array/FindTheLargestThreeElementsInAnArray.ts
Labels: triage, LOC: S

#5223 Auto Create Issue - 9
  program/data/programs.json
  program/program/find-the-smallest-three-elements-in-an-array/README.md
Labels: triage, LOC: S

#5215 Reverse words perl
  program/program/reverse-words-in-a-string/reverse_words_in_a_string.pl
Labels: triage, LOC: S

#5216 Ternary search fsharp
  program/program/implement-ternary-search/ImplementTernarySearch.fs
Labels: triage, LOC: S

#5217 Largest three elements
  program/program/find-the-largest-three-elements-in-an-array/FindTheLargestThreeElementsInAnArray.js
Labels: triage, LOC: S

#5218 #5207 binary search implementation
  program/program/implement-binary-search/implement_binary_search.py
Labels: triage, LOC: S

#5221 Implemented Binary Search in Dart
  program/program/implement-binary-search/implement_binary_search.dart
Labels: triage, LOC: M

#5220 Implemented Binary Search in implement_binary_search.rs
  program/program/implement-binary-search/implement_binary_search.rs
Labels: triage, LOC: M

#5219 Implemented Binary Search in ImplementBinarySearch.cpp
  program/program/implement-binary-search/ImplementBinarySearch.cpp
Labels: triage, LOC: M

#5245 Program for Binary Search in java
  program/program/implement-binary-search/ImplementBinarySearch.java
Labels: triage, LOC: M

#5247 Fix issue #5236 : The function has been tested in an online php Compiler
  program/program/find-the-smallest-three-elements-in-an-array/find_the_smallest_three_elements_in_an_array.php
Labels: triage, LOC: S

#5246 feat: add function that outputs two largest elements
  program/program/find-largest-two-elements-in-an-array/FindLargestTwoElementsInAnArray.js
Labels: triage, LOC: S

#5249 #5237 Python Solution to find the smallest three elements in array
  program/program/find-the-smallest-three-elements-in-an-array/find_the_smallest_three_elements_in_an_array.py
Labels: triage, LOC: S

#5248 Added the code to output small elements in an array using c++
  program/program/find-the-smallest-three-elements-in-an-array/FindTheSmallestThreeElementsInAnArray.cpp
Labels: triage, LOC: S

#5254 Auto Create Issue - 10
  program/data/programs.json
  program/program/implement-jump-search/README.md
Labels: triage, LOC: M

#5251 Write a JavaScript program to find the smallest three elements in an …
  program/program/find-the-smallest-three-elements-in-an-array/FindTheSmallestThreeElementsInAnArray.js
  program/program/reverse-words-in-a-string/reverseWordsInAString.js
Labels: triage, LOC: S

#5252 Issues Fixed : #5236 #5077 #5174 #5070
  program/program/find-the-smallest-two-elements-in-an-array/find_the_smallest_two_elements_in_an_array.c
  program/program/find-the-smallest-two-elements-in-an-array/find_the_smallest_two_elements_in_an_array.java
  program/program/find-the-smallest-two-elements-in-an-array/find_the_smallest_two_elements_in_an_array.php
Labels: triage, LOC: M

#5283 Rename files
  program/program/find-the-smallest-two-elements-in-an-array/FindTheSmallestTwoElementsInAnArray.c
  program/program/find-the-smallest-two-elements-in-an-array/FindTheSmallestTwoElementsInAnArray.java
  program/program/reverse-words-in-a-string/ReverseWordsInAString.js
Labels: triage, LOC: XS

#5287 Added R program for finding the largest three elements [#5181]
  program/program/find-the-largest-three-elements-in-an-array/find_the_largest_three_elements_in_an_array.r
Labels: triage, LOC: S

#5285 Implemented jump search program in TypeScript
  program/program/implement-jump-search/ImplementJumpSearch.ts
Labels: triage, LOC: M

#5281 My branch
  program/program/find-the-smallest-three-elements-in-an-array/findTheSmallestThreeElementsInAnArray.java
Labels: triage, LOC: M

#5290 Auto Create Issue - 11
  program/data/programs.json
  program/program/implement-linear-search/README.md
Labels: triage, LOC: M

#5312 Fix: collect program data workflow
  .github/workflows/collect-program-data.yml
Labels: triage, LOC: XS

#5288 Added C program for finding the smallest three elements [#5224]
  program/program/find-the-smallest-three-elements-in-an-array/FindTheSmallestThreeElementsInAnArray.c
Labels: triage, LOC: M

#5278 Implement jump search
  program/program/implement-jump-search/implement-jump-search.py
Labels: triage, LOC: S

#5284 Added CPP program that implements Ternary Search [#5112]
  program/program/implement-ternary-search/ImplementTernarySearch.cpp
Labels: triage, LOC: M

#5286 Added C program that implements Binary Search [#5194]
  program/program/implement-binary-search/ImplementBinarySearch.c
Labels: triage, LOC: M

#5282 Added R program that implements Ternary Search [#5124]
  program/program/implement-ternary-search/implement_ternary_search.r
Labels: triage, LOC: M

#5279 Added CPP program for finding the largest three elements
  program/program/find-the-largest-three-elements-in-an-array/FindTheLargestThreeElementsInAnArray.cpp
Labels: triage, LOC: M

#5318 Feature/ternary search implementation
  program/program/implement-ternary-search/implement_ternary_search.php
Labels: triage, LOC: M

#5319 Implement Jump Search algorithm in java
  program/program/implement-jump-search/ImplementJumpSearch.java
Labels: triage, LOC: M

#5321 Create FindTheLargestThreeElementsInAnArray.kt
  program/program/find-the-largest-three-elements-in-an-array/FindTheLargestThreeElementsInAnArray.kt
Labels: triage, LOC: S

#5328 Auto Create Issue - 12
  program/data/programs.json
  program/program/implement-selection-sort/README.md
Labels: triage, LOC: M

#5325 Create FindTheLargestTwoElementsInAnArray.kt
  program/program/find-the-largest-two-elements-in-an-array/FindTheLargestTwoElementsInAnArray.kt
Labels: triage, LOC: S

#5324 Create FindTheSmallestThreeElementsInAnArray.kt
  program/program/find-the-smallest-three-elements-in-an-array/FindTheSmallestThreeElementsInAnArray.kt
Labels: triage, LOC: S

#5326 Implemented linear search in C++
  program/program/implement-linear-search/ImplementLinearSearch.cpp
Labels: triage, LOC: S

#5322 Implement Linear Search in Kotlin
  program/program/implement-linear-search/ImplementLinearSearch.kt
Labels: triage, LOC: S

#5323 #5304 python linear search
  program/program/implement-linear-search/implement_linear_search.py
Labels: triage, LOC: M

#5352 Create ImplementLinearSearch.java
  program/program/implement-linear-search/ImplementLinearSearch.java
Labels: triage, LOC: S

#5350 #5299 js linear search
  program/program/implement-linear-search/ImplementLinearSearch.js
Labels: triage, LOC: S

#5351 #5310 TS linear search
  program/program/implement-linear-search/ImplementLinearSearch.ts
Labels: triage, LOC: S

#5353 #5342 python selection sort
  program/program/implement-selection-sort/implement_selection_sort.py
Labels: triage, LOC: M

#5354 Implemented linear search in rust
  program/program/implement-linear-search/ImplementLinearSearch.rs
Labels: triage, LOC: S

#5358 Added C program that implements linear search [#5291]
  program/program/implement-linear-search/ImplementLinearSearch.c
Labels: triage, LOC: M

#5357 Implemented Selection Sort program in PHP
  program/program/implement-selection-sort/implement_selection_sort.php
Labels: triage, LOC: M

#5356 Ternary search implementation
  program/program/implement-ternary-search/implement_ternary_search.py
Labels: triage, LOC: M

#5360 Selection sort java
  program/program/implement-selection-sort/ImplementSelectionSort.java
Labels: triage, LOC: M

#5359 feat: Created file LinearSearch on C#
  program/program/implement-linear-search/ImplementLinearSearch.cs
Labels: triage, LOC: M

#5362 Jump search
  program/program/implement-jump-search/ImplementJumpSearch.js
Labels: triage, LOC: M

#5363 feat(add): russian lang
  README.md
  translations/README-cn.md
  translations/README-fr.md
  translations/README-it.md
  translations/README-pt-br.md
  translations/README-ru.md
Labels: documentation, triage, LOC: L

#5365 Create ImplementSelectionSort.c
  program/program/implement-selection-sort/ImplementSelectionSort.c
Labels: triage, LOC: M

#5367 Implement Ternary Search algorithm in JavaScript
  program/program/implement-ternary-search/ImplementTernarySearch.js
Labels: triage, LOC: M

#5370 implement_linear_search.php
  program/program/implement-linear-search/implement_linear_search.php
Labels: triage, LOC: S

#5371 implementBinarySearch.scala
  program/program/implement-binary-search/implementBinarySearch.scala
Labels: triage, LOC: M

#5368 implement_selection_sort.rs
  program/program/implement-selection-sort/implement_selection_sort.rs
Labels: triage, LOC: M

#5372 Create ImplementTernarySearch.c
  program/program/implement-ternary-search/ImplementTernarySearch.c
Labels: triage, LOC: M

#5374 Feature/ternary search ruby
  program/program/implement-ternary-search/ImplementTernarySearch.rb
Labels: triage, LOC: M

#5366 Added File ImplementLinearSearch.rb to implement Linear Search in Ruby #5306
  program/program/implement-linear-search/ImplementLinearSearch.rb
Labels: triage, LOC: M

#5373 find_the_largest_three_elements_in_an_array.dart
  program/program/find-the-largest-three-elements-in-an-array/find_the_largest_three_elements_in_an_array.dart
Labels: triage, LOC: M

#5379 implement_jump_search.php
  program/program/implement-jump-search/implement_jump_search.php
Labels: triage, LOC: M

#5378 move_all_zeroes_to_end_of_array.php
  program/program/move-all-zeroes-to-end-of-array/move_all_zeroes_to_end_of_array.php
Labels: triage, LOC: M

#5383 FindTheLargestTwoElementsInAnArray.cpp
  program/program/find-the-largest-two-elements-in-an-array/FindTheLargestTwoElementsInAnArray.cpp
Labels: triage, LOC: M

#5376 Find the largest two elements in an array
  program/program/find-the-largest-two-elements-in-an-array/FindTheLargestTwoElementsInAnArray.c
Labels: triage, LOC: M

#5381 find_sum_of_numbers_by_recursion.php
  program/program/find-sum-of-numbers-by-recursion/find_sum_of_numbers_by_recursion.php
Labels: triage, LOC: S

#5384 Create ImplementJumpSearch.cs
  program/program/implement-jump-search/ImplementJumpSearch.cs
Labels: triage, LOC: M

#5385 FindTheSmallestTwoElementsInAnArray.cpp
  program/program/find-the-smallest-two-elements-in-an-array/FindTheSmallestTwoElementsInAnArray.cpp
Labels: triage, LOC: M

#5389 Create find_the_largest_three_elements_in_an_array.rs
  program/program/find-the-largest-three-elements-in-an-array/find_the_largest_three_elements_in_an_array.rs
Labels: triage, LOC: S

#5387 Create convert_octal_to_binary.dart
  program/program/convert-octal-to-binary/convert_octal_to_binary.dart
Labels: triage, LOC: M

#5382 Create ImplementJumpSearch.cpp
  program/program/implement-jump-search/ImplementJumpSearch.cpp
Labels: triage, LOC: M

#5391 Create ImplementLinearSearch.swift
  program/program/implement-linear-search/ImplementLinearSearch.swift
Labels: triage, LOC: M

#5380 Implemented Move All Zeroes To End Of Array in C
  program/program/move-all-zeroes-to-end-of-array/MoveAllZeroesToEndOfArray.c
Labels: triage, LOC: M

#5390 findTheSmallestThreeElementsInAnArray.scala
  program/program/find-the-smallest-three-elements-in-an-array/findTheSmallestThreeElementsInAnArray.scala
Labels: triage, LOC: M

#5386 find_the_largest_two_elements_in_an_array.php
  program/program/find-the-largest-two-elements-in-an-array/find_the_largest_two_elements_in_an_array.php
Labels: triage, LOC: M

#5377 Implement jump search in c
  program/program/implement-jump-search/ImplementJumpSearch.c
  program/program/implement-jump-search/ImplementJumpSearch.java
Labels: triage, LOC: M

#5361 Fix codinasion#5332: Write a Dart program to implement selection sort
  program/program/implement-linear-search/implement_linear_search.dart
  program/program/implement-selection-sort/implement_selection_sort.dart
Labels: triage, LOC: M

#5393 Ternary search implementation
  program/program/implement-ternary-search/implement_ternary_search.rs
Labels: triage, LOC: M

#5396 Fixes: #5073, #5038 & #5227
  program/program/find-the-largest-two-elements-in-an-array/find_the_largest_two_elements_in_an_array.dart
  program/program/find-the-smallest-three-elements-in-an-array/find_the_smallest_three_elements_in_an_array.dart
  program/program/find-the-smallest-two-elements-in-an-array/find_the_smallest_two_elements_in_an_array.dart
Labels: triage, LOC: L

#5397 Smallest three elements
  program/program/find-the-smallest-three-elements-in-an-array/FindTheSmallestThreeElementsInAnArray.rb
Labels: triage, LOC: XS

#5399 Implemented selection sort in kotlin
  program/program/implement-selection-sort/ImplementSelectionSort.kt
Labels: triage, LOC: M

#5405 Implemented jump search algorithm in dart
  program/program/implement-jump-search/implement_jump_search.dart
Labels: triage, LOC: M

#5400 Write a PHP program to print number to words in indian numbering system #1051
  program/program/print-number-to-words-in-indian-numbering-system/print_number_to_words_in_indian_numbering_system.php
Labels: triage, LOC: M

#5404 Implementing Selection sort in julia
  program/program/implement-selection-sort/ImplementSelectionSort.jl
Labels: triage, LOC: S

#5401 PHP convert a string to an int (without using built functions) #1841
  program/program/convert-a-string-to-an-integer-(without-using-built-in-functions)/convert_a_string_to_an_integer_(without_using_built-in_functions).php
Labels: triage, LOC: M

#5409 Smallest three elements
  program/program/find-the-smallest-three-elements-in-an-array/find_the_smallest_three_elements_in_an_array.pl
Labels: triage, LOC: S

#5410 Program: find_cube_of_a_number
  program/program/find-cube-of-a-number/find_cube_of_a_number.R
Labels: triage, LOC: S

#5412 Added R program to convert Hexadecimal to Binary
  program/program/convert-hexadecimal-to-binary/convert_hexadecimal_to_binary.r
Labels: triage, LOC: M

#5411 ConvertStringToReversecase.swift
  program/program/convert-string-to-reversecase/ConvertStringToReversecase.swift
Labels: triage, LOC: S

#5408 findSumOfApSeries.scala
  program/program/find-sum-of-ap-series/findSumOfApSeries.scala
Labels: triage, LOC: S

#5416 Smallest two elements
  program/program/find-the-smallest-two-elements-in-an-array/FindTheSmallestTwoElementsInAnArray.rb
Labels: triage, LOC: XS
