Repository codinasion/codinasion, pull requests merged in 2024-07, with the labels that each got.

#5767 Selection sort in Perl
  program/program/implement-selection-sort/implement_selection_sort.pl
Labels: triage, LOC: M

#5768 Selection sort in Haskell
  program/program/implement-selection-sort/implement_selection_sort.hs
Labels: triage, LOC: S

#5770 Linear search in Haskell
  program/program/implement-linear-search/implement_linear_search.hs
Labels: triage, LOC: S

#5772 Jump search in R
  program/program/implement-jump-search/implement_jump_search.r
Labels: triage, LOC: M

#5741 PR for issue #2498, #1992 #2309
  program/program/calculate-the-combination-of-n-objects-taken-r-at-a-time/Program/CalculateTheCombinationOfNObjectsTakenRAtATime.kt
  program/program/convert-string-to-snakecase/Program/ConvertStringToSnakecase.kt
  program/program/find-digital-root-of-a-number/FindDigitalRootOfANumber/.gitignore
  program/program/find-digital-root-of-a-number/FindDigitalRootOfANumber/.mvn/wrapper/maven-wrapper.jar
  program/program/find-digital-root-of-a-number/FindDigitalRootOfANumber/.mvn/wrapper/maven-wrapper.properties
  program/program/find-digital-root-of-a-number/FindDigitalRootOfANumber/mvnw
  program/program/find-digital-root-of-a-number/FindDigitalRootOfANumber/mvnw.cmd
  program/program/find-digital-root-of-a-number/FindDigitalRootOfANumber/pom.xml
  program/program/find-digital-root-of-a-number/FindDigitalRootOfANumber/src/main/kotlin/com/example/finddigitalrootofanumber/HelloApplication.kt
  program/program/find-digital-root-of-a-number/FindDigitalRootOfANumber/src/main/kotlin/com/example/finddigitalrootofanumber/HelloController.kt
  program/program/find-digital-root-of-a-number/FindDigitalRootOfANumber/src/main/kotlin/module-info.java
  program/program/find-digital-root-of-a-number/FindDigitalRootOfANumber/src/main/resources/com/example/finddigitalrootofanumber/hello-view.fxml
  program/program/find-the-rank-of-a-matrix/FindTheRankOfAMatrix/.gitignore
  program/program/find-the-rank-of-a-matrix/FindTheRankOfAMatrix/.mvn/wrapper/maven-wrapper.jar
  program/program/find-the-rank-of-a-matrix/FindTheRankOfAMatrix/.mvn/wrapper/maven-wrapper.properties
  program/program/find-the-rank-of-a-matrix/FindTheRankOfAMatrix/mvnw
  program/program/find-the-rank-of-a-matrix/FindTheRankOfAMatrix/mvnw.cmd
  program/program/find-the-rank-of-a-matrix/FindTheRankOfAMatrix/pom.xml
  program/program/find-the-rank-of-a-matrix/FindTheRankOfAMatrix/src/main/kotlin/com/example/findtherankofamatrix/HelloApplication.kt
  program/program/find-the-rank-of-a-matrix/FindTheRankOfAMatrix/src/main/kotlin/com/example/findtherankofamatrix/HelloController.kt
  program/program/find-the-rank-of-a-matrix/FindTheRankOfAMatrix/src/main/kotlin/module-info.java
  program/program/find-the-rank-of-a-matrix/FindTheRankOfAMatrix/src/main/resources/com/example/findtherankofamatrix/hello-view.fxml
Labels: triage, LOC: XXL

#5773 Ternary search in Swift
  program/program/implement-ternary-search/ImplementTernarySearch.swift
Labels: triage, LOC: M

#5774 Ternary search in Scala
  program/program/implement-ternary-search/implementTernarySearch.scala
Labels: triage, LOC: M
