Repository codinasion/codinasion, pull requests merged in 2024-02, with the labels that each got.

#5418 Move zeros to end
  program/program/move-all-zeroes-to-end-of-array/MoveAllZeroesToEndOfArray.rb
Labels: triage, LOC: S

#5429 feat: write a go program to find the largest two elements on the array #5040
  program/program/find-the-largest-two-elements-in-an-array/find_the_largest_two_elements_in_an_array.go
Labels: triage, LOC: S

#5430 feat(go): add program for largest three elements in array #5172
  program/program/find-the-largest-three-elements-in-an-array/find_the_largest_three_elements_in_an_array.go
Labels: triage, LOC: S

#5417 Largest 3 elements
  program/program/find-the-largest-three-elements-in-an-array/FindTheLargestThreeElementsInAnArray.fs
Labels: triage, LOC: S

#5434 feat(go): smallest three elements in an array #5229
  program/program/find-the-smallest-three-elements-in-an-array/find_the_smallest_three_elements_in_an_array.go
Labels: triage, LOC: S

#5435 feat(go): smallest two elements in an array #5075
  program/program/find-the-smallest-two-elements-in-an-array/find_the_smallest_two_elements_in_an_array.go
Labels: triage, LOC: S

#5414 A C++ program to move all zeroes to end of array
  program/program/move-all-zeroes-to-end-of-array/MoveAllZeroesToEndOfArray.cpp
  program/program/move-all-zeroes-to-end-of-array/move_all_zeroes_to_end_of_array.dart
Labels: triage, LOC: M

#5420 Smallest two elements
  program/program/find-the-smallest-two-elements-in-an-array/FindTheSmallestTwoElementsInAnArray.fs
Labels: triage, LOC: S

#5443 Written code to find sum of ap series in R language. #3281
  program/program/find-sum-of-ap-series/find_sum_of_ap_series.r
Labels: triage, LOC: S

#5442 Written code to print numbers from n to 1 without using loop in R lan…
  program/program/print-numbers-from-n-to-1-without-using-a-loop/print_numbers_from_n_to_1_without_using_a_loop.r
Labels: triage, LOC: S

#5422 Largest & smallest in an array
  program/program/find-largest-and-smallest-numbers-in-an-array/FindLargestAndSmallestNumbersInAnArray.fs
Labels: triage, LOC: S

#5424 FindAverageOfNumbersByRecursion
  program/program/find-average-of-numbers-by-recursion/FindAverageOfNumbersByRecursion
Labels: triage, LOC: S

#5433 ImplementBinarySearch.cs
  program/program/implement-binary-search/ImplementBinarySearch.cs
Labels: triage, LOC: M

#5444 Feature/move zeroes to end
  program/program/find-the-maximum-sum-of-a-contiguous-subarray/FindTheMaximumSumOfAContiguousSubarray.js
Labels: triage, LOC: S

#5428 R convert seconds to minutes
  program/program/convert-seconds-to-minutes/convert_seconds_to_minutes.r
Labels: triage, LOC: M

#5438 Written code for move zeroes to end of array in R language. #5149
  program/program/move-all-zeroes-to-end-of-array/move_all_zeroes_to_end_of_array.r
Labels: triage, LOC: S

#5431 feat(go): implement binary search #5199
  program/program/implement-binary-search/implement_binary_search.go
Labels: triage, LOC: M

#5425 FindTheMaximumSumOfAContiguousSubarray
  program/program/find-the-maximum-sum-of-a-contiguous-subarray-(kadanes-algorithm)/FindTheMaximumSumOfAContiguousSubarray
Labels: triage, LOC: S

#5448 function implemented
  program/program/reverse-words-in-a-string/ReverseWordsInAString.kt
Labels: triage, LOC: S

#5421 Largest 2 elements
  program/program/find-the-largest-two-elements-in-an-array/FindTheLargestTwoElementsInAnArray.fs
Labels: triage, LOC: XS

#5451 Smallest two elements
  program/program/find-the-smallest-two-elements-in-an-array/find_the_smallest_two_elements_in_an_array.pl
Labels: triage, LOC: S

#5450 Move all zeroes to end of array
  program/program/move-all-zeroes-to-end-of-array/MoveAllZeroesToEndOfArray.cs
Labels: triage, LOC: M

#5436 Written the code for largest two elements in an array in R language. …
  program/program/find-the-largest-two-elements-in-an-array/find_the_largest_two_elements_in_an_array.r
Labels: triage, LOC: M

#5453 Largest 2 elements
  program/program/find-the-largest-two-elements-in-an-array/find_the_largest_two_elements_in_an_array.pl
Labels: triage, LOC: S

#5446 Move zeroes to end array
  program/program/move-all-zeroes-to-end-of-array/MoveAllZeroesToEndOfArray.fs
Labels: triage, LOC: S

#5415 Upgrade probot from 12.3.3 to 13.0.0
  bot/package.json
Labels: triage, LOC: XS

#5447 Feature/move zeroes to end
  program/program/move-all-zeroes-to-end-of-array/MoveAllZeroesToEndOfArray.js
Labels: triage, LOC: S
